CREATE TABLE IF NOT EXISTS tileset (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
);

CREATE TABLE IF NOT EXISTS tiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tileset_id INTEGER,
    FOREIGN KEY (tileset_id) REFERENCES tileset(id) ON DELETE CASCADE
);

